spring:
  datasource:
    url: jdbc:h2:file:C:\Users\hv3\Music\BookYourPark\BookYourPark
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      use-new-id-generator-mappings: false
    naming:
      physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
      dialect: "org.hibernate.dialect.H2Dialect"
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      indent-output: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: vhemantharajan@gmail.com
    password: Hema*1999
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
