spring:
  datasource:
    url: jdbc:h2:file:C:\Users\hv3\Music\bookingwithlombook\booking
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: "/h2"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true


